from flask import Flask, render_template, request, jsonify
from investigate import investigate_goal, call_on_form_post
from hammurabi.us.fed.tax.indiv import withholding as withholding
from directory_tree import make_tree
from pathlib import PurePath



app = Flask(__name__)

#keep it secret, keep it safe
#generated by secrets.token_hex() function from secrets module
app.secret_key = '5555bf3986fa767556a744c5123afbaf8807a012b0fa45260a6fd18c919d648e'




@app.route("/")
def show_dir_tree():
    # path = os.path.expanduser(u'~')
    path = PurePath("/hammurabi/")
    # return str(path)
    return render_template('dir_tree.html', tree=make_tree(path))



@app.route("/investigate")
def call_investigate():
    return investigate_goal()

   

@app.route("/investigate", methods=['POST'])
def call_investigate_post():
    return call_on_form_post()

if __name__ == '__main__':
  app.run()
